name: Deploy DocC

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "docc"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26
    env:
      DEVELOPER_DIR: "/Applications/Xcode_26.4.1.app/Contents/Developer"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Configure SPM cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/Library/Caches/org.swift.swiftpm
          key: spm-${{ hashFiles('Package.swift') }}
          restore-keys: |
            spm-
      - name: Build DocC
        run: |
          make build_docc
      - name: Copy latest appcast.xml
        run: |
          cp sparkle/appcast.xml docs/appcast.xml
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: docs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
