name: Deploy DocC

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "docc"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26
    env:
      DEVELOPER_DIR: "/Applications/Xcode_26.4.app/Contents/Developer"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Configure SPM cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ~/Library/Caches/org.swift.swiftpm
          key: spm-${{ hashFiles('Package.swift') }}
          restore-keys: |
            spm-
      - name: Build DocC
        run: |
          make build_docc
      - name: Copy latest appcast.xml
        run: |
          cp sparkle/appcast.xml docs/appcast.xml
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: docs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
